In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

%matplotlib inline 

### Step:01 Input data

In [2]:
trainData = np.array([[0,1,0],
                      [0,1,1],
                      [0,0,0],
                      [10,0,0],
                      [10,1,1],
                      [10,0,1]
                     ])

In [6]:
outTrainData = np.array([[0], [0],[0],[1],[1],[1]])

In [4]:
trainDataPrediction = np.array([1,1,0])

In [5]:
trainDataPrediction

array([1, 1, 0])

In [11]:
testData = np.array([[1,1,1],
                      [10,0,1],
                      [0,1,10],
                      [10,0,10],
                      [10,0,10],
                      [0,0,0],
                      [0,1,1]
                     ])

In [15]:
outTestData = np.array([[0], [0],[0],[1],[1],[1]])

In [16]:
scalling = MinMaxScaler()

In [17]:
trainDataScaled=scalling.fit_transform(trainData)
testDataScaled=scalling.fit_transform(testData)


out_DataScaled=scalling.fit_transform(outTrainData)
out_ataScaled=scalling.fit_transform(outTestData)

In [18]:
trainDataScaled

array([[0.1, 1. , 0.1],
       [1. , 0. , 0.1],
       [0. , 1. , 1. ],
       [1. , 0. , 1. ],
       [1. , 0. , 1. ],
       [0. , 0. , 0. ],
       [0. , 1. , 0.1]])

In [19]:
trainData

array([[ 1,  1,  1],
       [10,  0,  1],
       [ 0,  1, 10],
       [10,  0, 10],
       [10,  0, 10],
       [ 0,  0,  0],
       [ 0,  1,  1]])

In [20]:
1/10

0.1

In [21]:
np.argmax([0.3,0.1,0.6])

2

In [22]:
a = [0.3,0.1,0.6]
a[2]

0.6

In [23]:
    trainImage = 1/255.0

In [24]:
trainImage

0.00392156862745098

In [25]:
pwd

'/home/user/Documents/ML_projects/Neural Network with Pytorch/CustomNeuralNetwork'